baseURL = "http://ilikeorangutans.github.io/"
languageCode = "en-ca"
title = "Jakob Külzer's Blog"
theme = "temple"

disqusShortname = "ilikeorangutans"

[permalinks]
  posts = "/:year/:month/:day/:slug"

[params]
  highlight = true

[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Jakob Külzer"
  github = "ilikeorangutans"
  email = "jakob.kuelzer@gmail.com"
