baseURL = "https://ilikeorangutans.github.io/"
languageCode = "en-ca"
title = "Jakob Külzer's Blog"
theme = "templefork"

disqusShortname = "ilikeorangutans"

enableGitInfo = true

[permalinks]
  posts = "/:year/:month/:day/:slug"

[params]
  highlight = true
  dateformat = "2006-01-02"
  dateformatpretty = "January 02 2006"

[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Jakob Külzer"
  github = "ilikeorangutans"
  email = "jakob.kuelzer@gmail.com"


