baseURL = "https://ilikeorangutans.github.io/"
languageCode = "en-ca"
title = "Jakob Külzer"
theme = "ilikeorangutans-hugo-theme"
copyright = "Jakob Külzer"

enableGitInfo = true

[markup]
  [markup.highlight]
    style = "rainbow_dash"

[permalinks]
  posts = "/:year/:month/:day/:slug"

[params]
  highlight = true
  dateformat = "2006-01-02"
  dateformatpretty = "January 02 2006"
[params.author]
    name = "Jakob Külzer"
    github = "ilikeorangutans"
    email = "jakob.kuelzer@gmail.com"

[taxonomies]
  tag = "tags"
  category = "categories"

[services]
  [services.disqus]
    shortname = "ilikeorangutans"

